name: Pyder Tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
    pythonVersion: 3.14.3

jobs:
    build:
        name: Pyder Tests (Ubuntu)
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Python ${{ env.pythonVersion }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ env.pythonVersion }}

          - name: Set up pnpm
            uses: pnpm/action-setup@v4
            with:
              version: 11.3.0
          
          - name: Install Python dependencies
            run: pip install -r requirements.txt
          
          - name: Run Tests
            run: python tests.py